products/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from django.conf.urls import patterns, include, url
import views, settings
from django.views.static import serve
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.user_login, name="login"),
    url(r'^create_product/$', views.create_product, name="create_product"),
    url(r'^create_category/$', views.create_category, name="create_category"),
    url(r'^create_material/$', views.create_material, name="create_material"),
    url(r'^create_manufacturer/$', views.create_manufacturer, name="create_manufacturer"),
    url(r'^view_product/(?P<product_id>\w+)/qr$', views.view_qrcode, name="view_product_qr"),
    url(r'^view_product/(?P<product_id>\w+)', views.view_product, name="view_product"),
    url(r'^activate/(?P<key>[a-zA-Z0-9_.-]+)/$', views.activate, name='activate'),
    url(r'^view_categories/$', views.view_categories, name="view_categories"),
    url(r'^view_materials/$', views.view_materials, name="view_materials"),
    url(r'^view_manufacturers/$', views.view_manufacturers, name="view_manufacturers"),
    url(r'^product_in_material/(?P<material_id>\w+)$', views.view_product_in_material, name="product_in_material"),
    url(r'^product_in_category/(?P<category_id>\w+)$', views.view_product_in_category, name="product_in_category"),
    url(r'^product_in_manufacturer/(?P<manufacturer_id>\w+)$', views.view_product_in_manufacturer, \
        name="product_in_manufacturer"),
    url(r'^all_products/$', views.all_products, name="all_products"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},name="logout"),
    url(r'^change_password/$', views.change_password, name="change_password"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^products/static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^products/media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

        # Examples:
    # url(r'^$', 'products.views.home', name='home'),
    # url(r'^products/', include('products.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

main/models.py
from django.db import models
# -*- coding: utf-8 -*-
from django.db import models
from django.forms.models import ModelChoiceField
import datetime
from django.contrib.auth.models import User
from django.contrib import admin
# Create your models here.

USER_STATUS = ((1, 'Active'), (2, 'Inactive'))
REGISTER_STATUS = (('Active', 'Active'), ('Inactive', 'Inactive'))
USER_PRIVILEDGES = ((1, 'Normal Member'), (2, 'Mod'))
PRODUCT_STATUS = ((1, 'Activated'), (2, 'Inactivated'))
# Create your models here.


class Register(models.Model):
    fullname = models.CharField('Fullname', max_length=250, blank=False)
    email= models.EmailField("Email", max_length=250, unique=True)
    status = models.CharField("Status", max_length=10, default='Inactive',
        choices=REGISTER_STATUS)
    register_date = models.DateField("Registration Date", default=datetime.date.today)
    username = models.CharField("Username", max_length=30, unique=True)
    activation_code = models.CharField("Registration code", max_length=30, default="")

    def __unicode__(self):
        return unicode(self.fullname)

    class Meta:
        verbose_name = u"Register"
        verbose_name_plural = u"Registers"


class Account(models.Model):
    username = models.OneToOneField(User, verbose_name="Username")
    fullname = models.CharField("Fullname", max_length=250, blank=False)
    email = models.EmailField("Email", max_length=250, unique=True)
    type = models.SmallIntegerField("User type", max_length=3, default=1,\
        choices=USER_PRIVILEDGES)
    status = models.IntegerField("Status", max_length=3, default=1,\
        choices=USER_STATUS)

    def __unicode__(self):
        return unicode(self.fullname)

    def get_info(self):
        return unicode(self.fullname) + u" - " + unicode(self.username)

    class Meta:
        verbose_name = u"Account"
        verbose_name_plural = u"Account"


class Manufacturer(models.Model):
    name = models.CharField("Name", max_length=50, unique=True, blank=False)
    description = models.CharField("Description", max_length=100)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = "Manufacturer"
        verbose_name_plural = "Manufacturer"


class Material(models.Model):
    name = models.CharField("Name", max_length=50, unique=True, blank=False)
    description = models.CharField("Description", max_length=100)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = "Material"
        verbose_name_plural = "Material"

class Category(models.Model):
    name = models.CharField("Category name", max_length=50, unique=True, blank=False)
    description = models.CharField("Description", max_length=100)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = "Product category"
        verbose_name_plural = "Product category"


class Product(models.Model):
    user_id = models.ForeignKey(User, verbose_name="Uploader", null=True)
    name = models.CharField("Name", default='Unnamed product', max_length=100)
    category_id = models.ForeignKey(Category, verbose_name=u"Category", null=True, blank=True)
    manufacturer_id = models.ForeignKey(Manufacturer, verbose_name=u"Manufacturer", null=True, blank=True)
    material_id = models.ForeignKey(Material, verbose_name=u"Material", null=True, blank=True)
    created_date = models.DateField("Created date", default=datetime.date.today)
    status = models.SmallIntegerField("Display status",
        max_length=3, choices=PRODUCT_STATUS, default=1)
    description = models.CharField("Description", max_length=200, blank=True)
    value = models.FloatField ("Estimated value", default=0)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Product"


admin.site.register(Account)
admin.site.register(Register)
admin.site.register(Product)
admin.site.register(Category)
admin.site.register(Manufacturer)
admin.site.register(Material)

products/views.py
import StringIO
import base64
from google.appengine.api import files
from google.appengine.ext import blobstore

__author__ = 'Loi'
# -*- coding: utf-8 -*-
import simplejson
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from main.forms import *
from django.core.urlresolvers import reverse
from main.models import *
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.db import transaction
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist
from datetime import date, datetime, timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from settings import MEDIA_ROOT
import random
import string
import qrcode
from utils import send_email, extract_fullname, get_account
ITEM_PER_PAGE = 25


def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))
    if request.method == 'POST':
        # validate the form
        form = AuthenticationForm(data=request.POST)
        print form.errors
        if form.is_valid():
            # log the user in
            login(request, form.get_user())
            return HttpResponseRedirect(reverse('index'))
    else:
        form = AuthenticationForm(request)

    context = RequestContext(request)
    response = render_to_response('login.html', {'form': form}, context_instance=context)
    return response


def index(request):
    context = RequestContext(request)
    response = render_to_response('index.html', {}, context_instance=context)
    return response


def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))
    else:
        message = ''
        # test new brance
        register_form = RegisterForm()
        if request.method == 'POST':
            data = request.POST.copy()
            activation_code = ''.join(random.choice(string.ascii_uppercase
                                                    + string.digits) for n in range(25))
            register_form = RegisterForm(data=data)
            if register_form.is_valid():
                try:
                    new_register = register_form.save(commit=False)
                    new_register.activation_code = activation_code
                    new_register.save()
                except Exception as e:
                    print e
                site = request.get_host()
                if site != 'localhost:8000':
                    site = 'http://' + site
                mail_message = u'Please access to %s/activate/%s/ to complete your registration.' \
                               % (site, activation_code)
                send_email(u'Registration at ' + unicode(site), mail_message, \
                    to_addr=[data['email']])

                success = True
                if request.is_ajax():
                    response = simplejson.dumps({
                        'success': success,
                        'message': message,
                        'redirect': reverse('index')
                    })
                    return HttpResponse(response, mimetype='json')
            else:
                message = u"Error at input\n"
                focus_id = ""
                try:
                    old_register = Register.objects.get(email=data['email'])
                    if old_register:
                        message += u': Registered email.'
                        focus_id = u"#id_email"
                except ObjectDoesNotExist:
                    try:
                        old_register = Register.objects.get(username=data['username'])
                        if old_register:
                            message += u': Username is not available.'
                            focus_id = u"#id_username"
                    except ObjectDoesNotExist:
                        pass
                    pass
                success = False
                if request.is_ajax():
                    response = simplejson.dumps({
                        'success': success,
                        'message': message,
                        'focus_id': focus_id,
                        })
                    return HttpResponse(response, mimetype='json')

        context = RequestContext(request)
        return render_to_response('register.html',
            {'message': message,
             'form': register_form},
            context_instance=context)


@transaction.commit_on_success
def activate(request, key):
    template_name = "activate.html"
    try:
        register = Register.objects.get(activation_code=key,
            status__exact='Inactive')
    except Exception as e:
        print e
        message = u'Invalid registration code or this account has been activated.'
        success = False
        return render_to_response(template_name,
            {'message':message, 'success':success})

    register.status='Active'
    register.save()
    message = u'Fullname: %s\nRegistration date: %s\nEmail: %s\n' % (register.fullname,\
                                                                     register.register_date,\
                                                                     register.email,)
    send_email(u'New registration', message,
        to_addr=['loi.luuthe@gmail.com'])
    first_name, last_name = extract_fullname(
        register.fullname)
    raw_password = ''.join(random.choice(string.ascii_letters
                                         + string.digits) for n in range(9))
    user = User.objects.create(
        username=register.username,
        password=make_password(raw_password),
        first_name=first_name,
        last_name=last_name)

    new_account = Account.objects.create(
        username=user,
        fullname=register.fullname,
        email=register.email)

    subject = u'Information of account'
    message = u'Information of account: \nUsername: %s\nPassword: %s\n\nHave nice time.' \
              % (unicode(new_account.username.username), unicode(raw_password))
    send_email(subject, message, to_addr=[new_account.email])

    message = u'Please check your email to get your registration information.'
    success = True
    return render_to_response(template_name,
        {'message': message, 'success' : success})

@transaction.commit_on_success
def create_product(request):
    try:
        user = request.user
    except Exception as e:
        print e
        return HttpResponseRedirect(reverse('login'))
    if not user.is_superuser:
        return HttpResponseRedirect(reverse('login'))
    product_form = ProductForm()
    if request.method == 'POST':
        data = request.POST.copy()
        product_form = ProductForm(data=data)
        if product_form.is_valid():
            try:
                new_product = product_form.save(commit=False)
                new_product.user_id = user
                new_product.save()
            except Exception as e:
                print e
                message = u"Error in input data."
                success = False
                if request.is_ajax():
                    response = simplejson.dumps({
                        'success': success,
                        'message': message
                    })
                    return HttpResponse(response, mimetype='json')

            success = True
            message = u"Successfully created new product."
            if request.is_ajax():
                response = simplejson.dumps({
                    'success': success,
                    'message': message,
                    'redirect': reverse('index')
                })
                return HttpResponse(response, mimetype='json')
        else:
            print product_form._errors
            message = u"Error in input data."
            success = False
            if request.is_ajax():
                response = simplejson.dumps({
                    'success': success,
                    'message': message
                })
                return HttpResponse(response, mimetype='json')

    context = RequestContext(request)
    return render_to_response('create_product.html',
        {'user': user,
         'form': product_form},
        context_instance=context)


def view_product(request, product_id):
    try:
        account = get_account(request)
    except Exception as e:
        account = None

    try:
        product = Product.objects.get(id=product_id, status__exact=1)
    except Exception as e:
        product = None

    context = RequestContext(request)
    return render_to_response('view_product.html',
        {'account': account,
         'product': product},
        context_instance=context)

def view_qrcode(request, product_id):
    product = Product.objects.get(id=product_id, status__exact=1)
    url = request.get_host()
    url = url + "/view_product/" + str(product.id)
    img = qrcode.make(url)
    out = StringIO.StringIO()
    img.save(out,"PNG")
    content = out.getvalue()
    out.close()
    file_name = product.name + '.png'
    response = HttpResponse(content,mimetype="image/png")
    response['Content-Disposition'] = 'attachment; filename="%s"' % (file_name)
    return response

def view_categories(request):
    objects = Category.objects.all()
    category_form = CategoryForm()
    paginator = Paginator(objects, ITEM_PER_PAGE) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        categories = paginator.page(page)
    except PageNotAnInteger:

products/templates/activate.html
{% extends 'base.html' %}

{% block content %}
    <div class="row-fluid">
        <div class="span10 alert alert-error">
            <div class="lead">{{ message }}</div>

            <a class="btn btn-primary btn-large" href="/"><i class="icon-home"></i> Trở về trang chủ</a>

            <a class="btn btn-warning btn-large" href="{% url "login" %}"><i class="icon-signin"></i> Đăng nhập để sử dụng hệ thống</a>
        </div>
    </div>
{% endblock %}

products/templates/change_password.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            function add_bootstrap_error(errs) {
                $.each(errs, function (key, val) {
                    var id = "#" + key;
                    var err_msg = '<span class="help-inline">' + val + '</span>';
                    $(id).after(err_msg);
                    $(id).parent().parent().addClass('error');
                });
            }
            function clear_bootstrap_error() {
                $(".error").removeClass('error');
                $("span.help-inline").remove();
            }
            $("form").submit(function(){
                $("#notify").showNotification("Sending data...", 20000);
                clear_bootstrap_error();
                var data = $(this).serialize();
                var args = { type:"POST",
                    url:"",
                    global:false,
                    data: data,
                    datatype:"json",
                    success:function (json) {
                        if (json.success) {
                            $("#notify").showNotification("Password change successfully", 2000);
                            window.location.replace({% url "login" %});
                        } else {
                            $("#notify").showNotification(json.message, 2000);
                            add_bootstrap_error(json.err);
                        }
                    },
                    error:function () {
                        $("#notify").showNotification("There is an error, please try again", 2000);
                    }
                };
                $.ajax(args);
                return false;
            });
        });
    </script>
{% endblock %}
{% block content %}
    <div class="row-fluid">
        <div class="span6">
            <form action="" class="well form-horizontal" id="product_form" method="post">{% csrf_token %}
                <legend>Change password</legend>
                {{ form|bootstrap }}
                <div class="form-actions">
                    <input id="submit" class="btn-danger" type="submit" value="Change password" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/create_category.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#submit").click(function(){
                var name = $("#id_name").val().replace(/^\s+|\s+$/g, '');
                if (name == "") {
                    $("#id_name").css('border-color', 'red');
                    $("#notify").showNotification("Name is required", 2000);
                    return false;
                } else $("#id_name").css('border-color', '#CCC');

                var description = $("#id_description").val().replace(/^\s+|\s+$/g, '');

                $("#notify").showNotification("Sending data...", 20000);
                var arg = { type:"POST",
                    url:"",
                    global:false,
                    data:{ name: name,
                        description: description,
                    },
                    datatype:"json",
                    success:function (json) {
                        if (json.success) {
                            $("#notify").showNotification(json.message, 2000);
                            window.location.replace(json.redirect);
                        } else {
                            $("#notify").showNotification(json.message, 2000);
                        }
                    },
                    error:function () {
                        $("#notify").showNotification("Gặp lỗi khi gửi đăng ký", 2000);
                    }
                };
                $.ajax(arg);
                return false;
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row-fluid">
        <div class="span6">
            <form action="" class="well form-horizontal" id="product_form" method="post">{% csrf_token %}
                <legend>New Category</legend>
                {{ form|bootstrap }}
                <div class="form-actions">
                    <input id="submit" class="btn-danger" type="submit" value="Create category" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/create_manufacturer.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#submit").click(function(){
                var name = $("#id_name").val().replace(/^\s+|\s+$/g, '');
                if (name == "") {
                    $("#id_name").css('border-color', 'red');
                    $("#notify").showNotification("Name is required", 2000);
                    return false;
                } else $("#id_name").css('border-color', '#CCC');

                var description = $("#id_description").val().replace(/^\s+|\s+$/g, '');

                $("#notify").showNotification("Sending data...", 20000);
                var arg = { type:"POST",
                    url:"",
                    global:false,
                    data:{ name: name,
                        description: description,
                    },
                    datatype:"json",
                    success:function (json) {
                        if (json.success) {
                            $("#notify").showNotification(json.message, 2000);
                            window.location.replace(json.redirect);
                        } else {
                            $("#notify").showNotification(json.message, 2000);
                        }
                    },
                    error:function () {
                        $("#notify").showNotification("Gặp lỗi khi gửi đăng ký", 2000);
                    }
                };
                $.ajax(arg);
                return false;
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row-fluid">
        <div class="span6">
            <form action="" class="well form-horizontal" id="product_form" method="post">{% csrf_token %}
                <legend>New Manufacturer</legend>
                {{ form|bootstrap }}
                <div class="form-actions">
                    <input id="submit" class="btn-danger" type="submit" value="Create manufacturer" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/create_material.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#submit").click(function(){
                var name = $("#id_name").val().replace(/^\s+|\s+$/g, '');
                if (name == "") {
                    $("#id_name").css('border-color', 'red');
                    $("#notify").showNotification("Name is required", 2000);
                    return false;
                } else $("#id_name").css('border-color', '#CCC');

                var description = $("#id_description").val().replace(/^\s+|\s+$/g, '');

                $("#notify").showNotification("Sending data...", 20000);
                var arg = { type:"POST",
                    url:"",
                    global:false,
                    data:{ name: name,
                        description: description,
                    },
                    datatype:"json",
                    success:function (json) {
                        if (json.success) {
                            $("#notify").showNotification(json.message, 2000);
                            window.location.replace(json.redirect);
                        } else {
                            $("#notify").showNotification(json.message, 2000);
                        }
                    },
                    error:function () {
                        $("#notify").showNotification("Gặp lỗi khi gửi đăng ký", 2000);
                    }
                };
                $.ajax(arg);
                return false;
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row-fluid">
        <div class="span6">
            <form action="" class="well form-horizontal" id="product_form" method="post">{% csrf_token %}
                <legend>New Material</legend>
                {{ form|bootstrap }}
                <div class="form-actions">
                    <input id="submit" class="btn-danger" type="submit" value="Create material" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/create_product.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block css %}
    <link href="/products/static/css/timepicker.css" rel="stylesheet" type="text/css"/>
    <link href="/products/static/css/datepicker.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block js %}
    <script type="text/javascript"
            src="/products/static/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_created_date").datepicker({
                format: 'yyyy-mm-dd',
                language: 'en'
            });
            
            $("#submit").click(function(){
                var date = $("#id_created_date").val().replace(/^\s+|\s+$/g, '');
                if (date == "") {
                    $("#id_created_date").css('border-color', 'red');
                    $("#notify").showNotification("Created date is require", 2000);
                    return false;
                } else $("#id_created_date").css('border-color', '#CCC');

                var name = $("#id_name").val().replace(/^\s+|\s+$/g, '');
                if (name == "") {
                    $("#id_name").css('border-color', 'red');
                    $("#notify").showNotification("Name is required", 2000);
                    return false;
                } else $("#id_name").css('border-color', '#CCC');

                var category_id = $("#id_category_id").val().replace(/^\s+|\s+$/g, '');
                var material_id = $("#id_material_id").val().replace(/^\s+|\s+$/g, '');
                var manufacturer_id = $("#id_manufacturer_id").val().replace(/^\s+|\s+$/g, '');
                var description = $("#id_description").val().replace(/^\s+|\s+$/g, '');

                var value = $("#id_value").val().replace(/^\s+|\s+$/g, '');
                if (value == "") {
                    $("#id_value").css('border-color', 'red');
                    $("#notify").showNotification("Value is required and a float number", 2000);
                    return false;
                } else $("#id_value").css('border-color', '#CCC');

                $("#notify").showNotification("Sending data...", 20000);
                var arg = { type:"POST",
                    url:"",
                    global:false,
                    data:{ name: name,
                        created_date: date,
                        category_id: category_id,
                        material_id: material_id,
                        manufacturer_id: manufacturer_id,
                        description: description,
                        value: value
                    },
                    datatype:"json",
                    success:function (json) {
                        if (json.success) {
                            $("#notify").showNotification(json.message, 2000);
                            window.location.replace(json.redirect);
                        } else {
                            $("#notify").showNotification(json.message, 2000);
                        }
                    },
                    error:function () {
                        $("#notify").showNotification("Gặp lỗi khi gửi đăng ký", 2000);
                    }
                };
                $.ajax(arg);
                return false;
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row-fluid">
        <div class="span6">
            <form action="" class="well form-horizontal" id="product_form" method="post">{% csrf_token %}
                <legend>New product</legend>
                {{ form|bootstrap }}
                <div class="form-actions">
                    <input id="submit" class="btn-danger" type="submit" value="Create product" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/index.html
{% extends "base.html" %}
{% block content %}
    Welcome to Product Management
{% endblock %}

products/templates/logout.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="REFRESH" content="0;url={% url "index" %}"></HEAD>
    <title></title>
</head>
<body>

</body>
</html>

products/templates/view_categories.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>
{% endblock %}

{% block content %}
    {% if categories %}
    <table  class="table table-striped">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
        </thead>
        {% for category in categories %}
            <tr>
                <td><a href="{% url "product_in_category" category.id%}" title="Go to see all products in this category">{{ category.id }}</a></td>
                <td>{{ category.name|default_if_none:""}}</td>
                <td>{{ category.description|default_if_none:""}}</td>
            </tr>
        {% endfor %}
    </table>

    <div class="pagination">
    <span class="step-links">
        {% if categories.has_previous %}
            <a href="?page={{ categories.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ categories.number }} of {{ categories.paginator.num_pages }}.
        </span>

        {% if categories.has_next %}
            <a href="?page={{ categories.next_page_number }}">next</a>
        {% endif %}
    </span>
    </div>
    {% else %}
        <h3>No categories</h3>
    {% endif %}
{% endblock %}